### ISSUE TITLE
Enable discussion

### ISSUE THREAD

**Issue by AthulNoobie** [xxzoltanxx/Balvan-Chat#1]
It will be good if you enable discussions in this repo. "Issue" is not good for discussions

**Comment by AthulNoobie** [comment]
I already mentioned a suggestions in reddit. Here is it again:
Super !!.
It will be nice if the user 1 and user 2 chats are seperated by left and right side. Like in WhatsApp.

It would be nice if this chat service is available as API. Then it can be integrated to websites or services.
Eg: A simple customer helpline chat in a big website.

Here is a small recommendation:

Convent your entire project to a python library and upload it in "pip". 

So we can import it and use it in our Flask web apps as "customer support" or "chat with us".

Or create a chat app by importing a single python module. That's cool right?

**Comment by xxzoltanxx** [comment]
Hi, thanks for your suggestions.
The one about separating chat bubbles was the idea at first, but I went the easy way regarding chat bubbles, just to make development easier at first.
About the second and third. I'm considering making this as an api too. This way it will make sense to make a pip package out of it.

I'm writing this in my file regarding possible new features.
The discussion page is up and running.

Have a nice day
